/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package database.sql;

import java.awt.Choice;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author AVINASH GURJAR
 */
public class TColName extends javax.swing.JFrame {
    
    TColName p;
     JButton x;
    JPanel jp,jp1;
    JLabel j1,j2;
    Choice t[];
JTextField b[];
String column[];
String data_type[];

    /**
     * Creates new form TColName
     */
    public TColName(int n) {
        initComponents();
        t=new Choice[n];
        p=this;
    b=new JTextField[n];
    column=new String[n];
    data_type=new String[n];
j1=new JLabel("             Column Name                                 ");

j2=new JLabel("                                                    Data Type");
jp=new JPanel();
jp.add(j1);
jp.add(j2);

add(jp);
jp=new JPanel();
//setLayout(new FlowLayout());
//setLayout(new FlowLayout(FlowLayout.RIGHT));
//setLayout(new FlowLayout(FlowLayout.LEFT,20,20));
for(int i=0;i<b.length;i++)
{
b[i]=new JTextField(20);
b[i].setFont(new Font("Century Gothic", Font.ITALIC, 20));
add(b[i]);
t[i]=new Choice();
t[i].setFont(new Font("Century Gothic", Font.ITALIC, 20));


// FOR adding items 

t[i].add("select type");
t[i].add("INTEGER");
t[i].add("VARCHAR");
t[i].add("FLOAT");





add(t[i]);


setLayout(new FlowLayout(FlowLayout.LEFT,30,15));

}
x=new JButton("        Submit       ");
x.setFont(new Font("Century Gothic", Font.ITALIC, 20));
x.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                
                for(int i=0;i<n;i++)
        {
            
            column[i]=b[i].getText();
            data_type[i]=t[i].getSelectedItem();
             System.out.println(column[i]+data_type[i]);
        }
                
                
                
                Database1 db=new Database1();
                  db.create_table(column, data_type);
                p.setVisible(false);
                new Manage().setVisible(true);
            }
        });
add(x);
setLocation(250,250);
    setResizable(false);
 setSize(600,600); 
        setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TColName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TColName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TColName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TColName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
